
                (function() {
                    var nodeEnv = typeof require !== 'undefined' && typeof process !== 'undefined';
                    var __module = nodeEnv ? module : {exports:{}};
                    var __filename = 'preview-scripts/__qc_index__.js';
                    var __require = nodeEnv ? function (request) {
                        return cc.require(request);
                    } : function (request) {
                        return __quick_compile_project__.require(request, __filename);
                    };
                    function __define (exports, require, module) {
                        if (!nodeEnv) {__quick_compile_project__.registerModule(__filename, module);}
require('./assets/migration/use_v2.1-2.2.1_cc.Toggle_event');
require('./assets/resources/shader/flash-light');
require('./assets/script/BulletE');
require('./assets/script/CoinItem');
require('./assets/script/Enemy');
require('./assets/script/EnergyItem');
require('./assets/script/Finish');
require('./assets/script/GameMain');
require('./assets/script/GameMap');
require('./assets/script/GameScene');
require('./assets/script/JoyStick');
require('./assets/script/Player');
require('./assets/script/Revive');
require('./assets/script/Setting');
require('./assets/script/SkillIcon');
require('./assets/script/StartScene');
require('./assets/script/TankE');
require('./assets/script/Upgrade');
require('./assets/script/ad/Analytics');
require('./assets/script/ad/BannerAd');
require('./assets/script/ad/InsertAd');
require('./assets/script/ad/JumpMini');
require('./assets/script/ad/Recorder');
require('./assets/script/ad/RewardAd');
require('./assets/script/ad/Share');
require('./assets/script/ad/admob/AdmobBannerAd');
require('./assets/script/ad/admob/AdmobInsertAd');
require('./assets/script/ad/admob/AdmobRewardAd');
require('./assets/script/ad/admob/AdmobShare');
require('./assets/script/ad/bytedance/TTBannerAd');
require('./assets/script/ad/bytedance/TTInsertAd');
require('./assets/script/ad/bytedance/TTRecorderEx');
require('./assets/script/ad/bytedance/TTRewardAd');
require('./assets/script/ad/bytedance/TTShareEx');
require('./assets/script/ad/wechat/WechatAnalytics');
require('./assets/script/ad/wechat/WechatBannerAd');
require('./assets/script/ad/wechat/WechatInsertAd');
require('./assets/script/ad/wechat/WechatRewardAd');
require('./assets/script/ad/wechat/WechatShare');
require('./assets/script/base/BaseComponent');
require('./assets/script/base/Dialogs');
require('./assets/script/base/LinkPrefab');
require('./assets/script/base/LocalizedData');
require('./assets/script/base/MusicManager');
require('./assets/script/base/Utils');
require('./assets/script/config/AD');
require('./assets/script/config/ADConfig');
require('./assets/script/config/Bullet');
require('./assets/script/config/Energy');
require('./assets/script/config/Level');
require('./assets/script/config/Music');
require('./assets/script/config/Tank');
require('./assets/script/sdk/Main');
require('./assets/script/sdk/cfw/interface/TextureRenderInterface');
require('./assets/script/sdk/engine/ScreenshotComp');
require('./assets/script/sdk/engine/TextureRenderUtils');
require('./assets/script/sdk/sdk/SDKConfig');
require('./assets/script/sdk/sdk/SDKManager');
require('./assets/script/sdk/sdk/base/BaseAd');
require('./assets/script/sdk/sdk/base/BaseChannel');
require('./assets/script/sdk/sdk/base/BaseLogin');
require('./assets/script/sdk/sdk/base/BaseNativeAdItemModel');
require('./assets/script/sdk/sdk/base/BaseRecorder');
require('./assets/script/sdk/sdk/base/BaseSDK');
require('./assets/script/sdk/sdk/base/BaseScreenshot');
require('./assets/script/sdk/sdk/base/BaseShare');
require('./assets/script/sdk/sdk/base/BaseSubPackage');
require('./assets/script/sdk/sdk/bd/BDChannel');
require('./assets/script/sdk/sdk/bd/BDRewardAd');
require('./assets/script/sdk/sdk/bd/BDScreenshot');
require('./assets/script/sdk/sdk/bd/BDSubPackage');
require('./assets/script/sdk/sdk/comp/BannerAdComp');
require('./assets/script/sdk/sdk/comp/InsertAdComp');
require('./assets/script/sdk/sdk/comp/InstallIconComp');
require('./assets/script/sdk/sdk/comp/JumpMiniComp');
require('./assets/script/sdk/sdk/comp/NativeAdItemView');
require('./assets/script/sdk/sdk/comp/NativeComp');
require('./assets/script/sdk/sdk/comp/RecorderComp');
require('./assets/script/sdk/sdk/comp/RewardAdComp');
require('./assets/script/sdk/sdk/comp/ScreenshotComponent');
require('./assets/script/sdk/sdk/comp/ShareComp');
require('./assets/script/sdk/sdk/data/ChannelItemModel');
require('./assets/script/sdk/sdk/dev/DevChannel');
require('./assets/script/sdk/sdk/oppo/OppoBannerAd');
require('./assets/script/sdk/sdk/oppo/OppoChannel');
require('./assets/script/sdk/sdk/oppo/OppoInsertAd');
require('./assets/script/sdk/sdk/oppo/OppoNativeAd');
require('./assets/script/sdk/sdk/oppo/OppoNativeAdItemModel');
require('./assets/script/sdk/sdk/oppo/OppoRewardAd');
require('./assets/script/sdk/sdk/oppo/OppoScreenshot');
require('./assets/script/sdk/sdk/oppo/OppoSubPackage');
require('./assets/script/sdk/sdk/qq/QQAppBoxAd');
require('./assets/script/sdk/sdk/qq/QQBanner');
require('./assets/script/sdk/sdk/qq/QQChannel');
require('./assets/script/sdk/sdk/qq/QQInterstitialAd');
require('./assets/script/sdk/sdk/qq/QQScreenshot');
require('./assets/script/sdk/sdk/qq/QQShare');
require('./assets/script/sdk/sdk/qq/QQSubPackage');
require('./assets/script/sdk/sdk/qq/QQVideoAd');
require('./assets/script/sdk/sdk/tt/TTBanner');
require('./assets/script/sdk/sdk/tt/TTChannel');
require('./assets/script/sdk/sdk/tt/TTInsertAd1');
require('./assets/script/sdk/sdk/tt/TTLogin');
require('./assets/script/sdk/sdk/tt/TTRecorder');
require('./assets/script/sdk/sdk/tt/TTScreenshot');
require('./assets/script/sdk/sdk/tt/TTShare');
require('./assets/script/sdk/sdk/tt/TTVideoAd');
require('./assets/script/sdk/sdk/vivo/VIvoInsertAd');
require('./assets/script/sdk/sdk/vivo/VivoBannerAd');
require('./assets/script/sdk/sdk/vivo/VivoChannel');
require('./assets/script/sdk/sdk/vivo/VivoNativeAd');
require('./assets/script/sdk/sdk/vivo/VivoRewardAd');
require('./assets/script/sdk/sdk/wx/WXBannerAd');
require('./assets/script/sdk/sdk/wx/WXChannel');
require('./assets/script/sdk/sdk/wx/WXInterstitialAd');
require('./assets/script/sdk/sdk/wx/WXRewardedVideoAd');
require('./assets/script/sdk/sdk/wx/WXScreenshot');
require('./assets/script/sdk/sdk/wx/WXShare');
require('./assets/script/sdk/sdk/wx/WXSubPackage');
require('./assets/script/sdk/sdk/wx/WXlogin');
require('./assets/script/sdk/test/BannerView');
require('./assets/script/sdk/test/FunctionView');
require('./assets/script/sdk/test/HomeView');
require('./assets/script/sdk/test/NativeView');
require('./assets/wish/Wish');

                    }
                    if (nodeEnv) {
                        __define(__module.exports, __require, __module);
                    }
                    else {
                        __quick_compile_project__.registerModuleFunc(__filename, function () {
                            __define(__module.exports, __require, __module);
                        });
                    }
                })();